import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "DDoS Radar",
    description: "Generated by SOREZ",
};

export const revalidate = 1;
export default function RootLayout({children}: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body className="bg-[#02071D] text-white">
        <div className="flex">
            <Sidebar/>
            <div className="flex-1 ml-24">
                <Navbar/>
                <main className="px-8">{children}</main>
            </div>
        </div>
        </body>
        </html>
    );
}
